matrix:
  include:
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
      branches:
      only:
        - master
      # command to install dependencies
      before_install:
         - npm update
      install:
        - pip install -r requirements.txt
        - npm install
      script:
        - pytest

    - language: node_js
      node_js:
        - stable
      before_script:
        - cd frontend
      branches:
      only:
        - master
      # command to install dependencies
      before_install:
         - npm update
      install:
        - npm install
      script:
        - npm run test
