language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r ./backend/requirements.txt

#format to deploy app using heroku
deploy:
  provider: heroku
  api_key:
    secure: "2c970c38-6e2c-40be-9716-4413ea9dcab8"
  app: OKBoomer
# command to run tests
script:
  - pytest
  
  
