matrix:
  include:
    # For django testing
    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
      branches:
      only:
        - master
      # command to install dependencies
      before_install:
         - npm update
      install:
        - pip install -r requirements.txt
        - npm install
      script:
        - pytest

    # For React.js testing
    - language: node_js
      node_js:
        - stable
      before_script:
        - cd frontend # package.json is in frontend directory
      branches:
      only:
        - master
      # command to install dependencies
      cache:
      directories:
      - node_modules
      before_install:
         - npm update
      install:
        - npm install
      script:
        - npm run test
